# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormUpdate(object):
    def setupUi(self, FormUpdate):
        FormUpdate.setObjectName("FormUpdate")
        FormUpdate.resize(392, 346)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormUpdate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FormUpdate)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pte_update_txt = QtWidgets.QPlainTextEdit(self.frame)
        self.pte_update_txt.setObjectName("pte_update_txt")
        self.gridLayout.addWidget(self.pte_update_txt, 0, 0, 1, 2)
        self.lb_title = QtWidgets.QLabel(self.frame)
        self.lb_title.setObjectName("lb_title")
        self.gridLayout.addWidget(self.lb_title, 1, 0, 1, 2)
        self.bt_no = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bt_no.setFont(font)
        self.bt_no.setObjectName("bt_no")
        self.gridLayout.addWidget(self.bt_no, 2, 0, 1, 1)
        self.bt_yes = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bt_yes.setFont(font)
        self.bt_yes.setObjectName("bt_yes")
        self.gridLayout.addWidget(self.bt_yes, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(FormUpdate)
        QtCore.QMetaObject.connectSlotsByName(FormUpdate)

    def retranslateUi(self, FormUpdate):
        _translate = QtCore.QCoreApplication.translate
        FormUpdate.setWindowTitle(_translate("FormUpdate", "Form"))
        self.lb_title.setText(_translate("FormUpdate", "发现新版本,是否更新?"))
        self.bt_no.setText(_translate("FormUpdate", "NO"))
        self.bt_yes.setText(_translate("FormUpdate", "YES"))
