# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_equip.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormEquip(object):
    def setupUi(self, FormEquip):
        FormEquip.setObjectName("FormEquip")
        FormEquip.resize(370, 309)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormEquip)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(FormEquip)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(FormEquip)
        QtCore.QMetaObject.connectSlotsByName(FormEquip)

    def retranslateUi(self, FormEquip):
        _translate = QtCore.QCoreApplication.translate
        FormEquip.setWindowTitle(_translate("FormEquip", "Form"))
