# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_team.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTeam(object):
    def setupUi(self, FormTeam):
        FormTeam.setObjectName("FormTeam")
        FormTeam.resize(573, 110)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormTeam)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(FormTeam)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.h_box = QtWidgets.QHBoxLayout()
        self.h_box.setContentsMargins(0, 0, 0, 0)
        self.h_box.setSpacing(0)
        self.h_box.setObjectName("h_box")
        self.verticalLayout.addLayout(self.h_box)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(FormTeam)
        QtCore.QMetaObject.connectSlotsByName(FormTeam)

    def retranslateUi(self, FormTeam):
        _translate = QtCore.QCoreApplication.translate
        FormTeam.setWindowTitle(_translate("FormTeam", "Form"))
