# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_doc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormDoc(object):
    def setupUi(self, FormDoc):
        FormDoc.setObjectName("FormDoc")
        FormDoc.resize(440, 305)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormDoc)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FormDoc)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_doc = QtWidgets.QLabel(self.frame)
        self.lb_doc.setText("")
        self.lb_doc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_doc.setWordWrap(True)
        self.lb_doc.setObjectName("lb_doc")
        self.horizontalLayout.addWidget(self.lb_doc)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(FormDoc)
        QtCore.QMetaObject.connectSlotsByName(FormDoc)

    def retranslateUi(self, FormDoc):
        _translate = QtCore.QCoreApplication.translate
        FormDoc.setWindowTitle(_translate("FormDoc", "Form"))
