# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_location.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormLocation(object):
    def setupUi(self, FormLocation):
        FormLocation.setObjectName("FormLocation")
        FormLocation.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormLocation)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(FormLocation)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.v_box = QtWidgets.QVBoxLayout(self.frame)
        self.v_box.setContentsMargins(0, 0, 0, 0)
        self.v_box.setSpacing(2)
        self.v_box.setObjectName("v_box")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(FormLocation)
        QtCore.QMetaObject.connectSlotsByName(FormLocation)

    def retranslateUi(self, FormLocation):
        _translate = QtCore.QCoreApplication.translate
        FormLocation.setWindowTitle(_translate("FormLocation", "Form"))
