# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_job_and_race.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormJobAndRace(object):
    def setupUi(self, FormJobAndRace):
        FormJobAndRace.setObjectName("FormJobAndRace")
        FormJobAndRace.resize(452, 256)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormJobAndRace)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(FormJobAndRace)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(FormJobAndRace)
        QtCore.QMetaObject.connectSlotsByName(FormJobAndRace)

    def retranslateUi(self, FormJobAndRace):
        _translate = QtCore.QCoreApplication.translate
        FormJobAndRace.setWindowTitle(_translate("FormJobAndRace", "Form"))
