# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSet(object):
    def setupUi(self, FormSet):
        FormSet.setObjectName("FormSet")
        FormSet.resize(260, 32)
        FormSet.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(FormSet)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FormSet)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(9, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_equip = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_equip.setFont(font)
        self.cb_equip.setChecked(True)
        self.cb_equip.setObjectName("cb_equip")
        self.horizontalLayout.addWidget(self.cb_equip)
        self.cb_location = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_location.setFont(font)
        self.cb_location.setChecked(True)
        self.cb_location.setObjectName("cb_location")
        self.horizontalLayout.addWidget(self.cb_location)
        self.cb_auto_start = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_auto_start.setFont(font)
        self.cb_auto_start.setObjectName("cb_auto_start")
        self.horizontalLayout.addWidget(self.cb_auto_start)
        self.cb_side = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_side.setFont(font)
        self.cb_side.setChecked(True)
        self.cb_side.setObjectName("cb_side")
        self.horizontalLayout.addWidget(self.cb_side)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(FormSet)
        QtCore.QMetaObject.connectSlotsByName(FormSet)

    def retranslateUi(self, FormSet):
        _translate = QtCore.QCoreApplication.translate
        FormSet.setWindowTitle(_translate("FormSet", "Form"))
        self.cb_equip.setToolTip(_translate("FormSet", "<html><head/><body><p><span style=\" color:#ffffff;\">是否显示推荐装备</span></p></body></html>"))
        self.cb_equip.setText(_translate("FormSet", "装备"))
        self.cb_location.setToolTip(_translate("FormSet", "<html><head/><body><p><span style=\" color:#ffffff;\">是否显示站位和早期过渡的棋子</span></p></body></html>"))
        self.cb_location.setText(_translate("FormSet", "站位"))
        self.cb_auto_start.setToolTip(_translate("FormSet", "<html><head/><body><p><span style=\" color:#ffffff;\">是否</span><span style=\" color:#ff007f;\">自动接受</span></p><p><span style=\" color:#ff007f;\">仅支持游戏大厅分辨率为</span><span style=\" color:#ff5500;\">16:9</span><span style=\" color:#ff007f;\">例如:</span></p><p><span style=\" color:#ff5500;\">1024*576</span></p><p><span style=\" color:#ff5500;\">1280*720</span></p><p><span style=\" color:#ff5500;\">1600*900</span></p><p><span style=\" color:#ff5500;\">1920*1080</span></p></body></html>"))
        self.cb_auto_start.setText(_translate("FormSet", "自动接受"))
        self.cb_side.setToolTip(_translate("FormSet", "<html><head/><body><p><span style=\" color:#ff007f;\">是否启用侧键热键功能</span></p><p><span style=\" color:#ff007f;\">如果你不需要使用侧键则不要勾选它</span></p><p><br/></p></body></html>"))
        self.cb_side.setText(_translate("FormSet", "侧键"))
