# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_doc_switch.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormDocSwitch(object):
    def setupUi(self, FormDocSwitch):
        FormDocSwitch.setObjectName("FormDocSwitch")
        FormDocSwitch.resize(355, 37)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormDocSwitch)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(FormDocSwitch)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_early = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_early.setFont(font)
        self.bt_early.setObjectName("bt_early")
        self.horizontalLayout_2.addWidget(self.bt_early)
        self.bt_d_time = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_d_time.setFont(font)
        self.bt_d_time.setObjectName("bt_d_time")
        self.horizontalLayout_2.addWidget(self.bt_d_time)
        self.bt_location = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_location.setFont(font)
        self.bt_location.setObjectName("bt_location")
        self.horizontalLayout_2.addWidget(self.bt_location)
        self.bt_enemy = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_enemy.setFont(font)
        self.bt_enemy.setObjectName("bt_enemy")
        self.horizontalLayout_2.addWidget(self.bt_enemy)
        self.bt_close = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_close.setFont(font)
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_2.addWidget(self.bt_close)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(FormDocSwitch)
        QtCore.QMetaObject.connectSlotsByName(FormDocSwitch)

    def retranslateUi(self, FormDocSwitch):
        _translate = QtCore.QCoreApplication.translate
        FormDocSwitch.setWindowTitle(_translate("FormDocSwitch", "Form"))
        self.bt_early.setText(_translate("FormDocSwitch", "早期"))
        self.bt_d_time.setText(_translate("FormDocSwitch", "D牌"))
        self.bt_location.setText(_translate("FormDocSwitch", "站位"))
        self.bt_enemy.setText(_translate("FormDocSwitch", "克制"))
        self.bt_close.setText(_translate("FormDocSwitch", "退出"))
