# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_nav.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNav(object):
    def setupUi(self, FormNav):
        FormNav.setObjectName("FormNav")
        FormNav.resize(176, 86)
        FormNav.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(FormNav)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FormNav)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.bt_confirmed = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_confirmed.setFont(font)
        self.bt_confirmed.setObjectName("bt_confirmed")
        self.gridLayout.addWidget(self.bt_confirmed, 7, 0, 1, 1)
        self.bt_strategy = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_strategy.setFont(font)
        self.bt_strategy.setObjectName("bt_strategy")
        self.gridLayout.addWidget(self.bt_strategy, 7, 1, 1, 1)
        self.bt_sponsorship = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_sponsorship.setFont(font)
        self.bt_sponsorship.setObjectName("bt_sponsorship")
        self.gridLayout.addWidget(self.bt_sponsorship, 5, 0, 1, 1)
        self.bt_strategy2 = QtWidgets.QPushButton(self.frame)
        self.bt_strategy2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bt_strategy2.setFont(font)
        self.bt_strategy2.setObjectName("bt_strategy2")
        self.gridLayout.addWidget(self.bt_strategy2, 5, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(FormNav)
        QtCore.QMetaObject.connectSlotsByName(FormNav)

    def retranslateUi(self, FormNav):
        _translate = QtCore.QCoreApplication.translate
        FormNav.setWindowTitle(_translate("FormNav", "Form"))
        self.bt_confirmed.setText(_translate("FormNav", "小队规划"))
        self.bt_strategy.setText(_translate("FormNav", "格斗大赛"))
        self.bt_sponsorship.setText(_translate("FormNav", "赞助懒人"))
        self.bt_strategy2.setText(_translate("FormNav", "隐秘海域"))
