# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_strategy_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormStrategyList(object):
    def setupUi(self, FormStrategyList):
        FormStrategyList.setObjectName("FormStrategyList")
        FormStrategyList.resize(456, 439)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormStrategyList)
        self.horizontalLayout.setProperty("contentsMargins", QtCore.QRect(0, 0, 0, 0))
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(FormStrategyList)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setProperty("contentsMargins", QtCore.QRect(2, 2, 2, 2))
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setObjectName("search_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.search_layout.addItem(spacerItem)
        self.search_input = QtWidgets.QLineEdit(self.frame)
        self.search_input.setAlignment(QtCore.Qt.AlignCenter)
        self.search_input.setObjectName("search_input")
        self.search_layout.addWidget(self.search_input)
        self.search_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setBold(True)
        font.setWeight(75)
        self.search_button.setFont(font)
        self.search_button.setObjectName("search_button")
        self.search_layout.addWidget(self.search_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.search_layout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.search_layout)
        self.tw_strategy_list = QtWidgets.QTableWidget(self.frame)
        self.tw_strategy_list.setRowCount(0)
        self.tw_strategy_list.setColumnCount(0)
        self.tw_strategy_list.setObjectName("tw_strategy_list")
        self.verticalLayout.addWidget(self.tw_strategy_list)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(FormStrategyList)
        QtCore.QMetaObject.connectSlotsByName(FormStrategyList)

    def retranslateUi(self, FormStrategyList):
        _translate = QtCore.QCoreApplication.translate
        FormStrategyList.setWindowTitle(_translate("FormStrategyList", "Form"))
        self.search_input.setPlaceholderText(_translate("FormStrategyList", "输入关键字 支持多条件 例如:卡莎 宗师"))
        self.search_button.setText(_translate("FormStrategyList", "往下查找"))
