# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item_chess.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemChess(object):
    def setupUi(self, ItemChess):
        ItemChess.setObjectName("ItemChess")
        ItemChess.resize(170, 165)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ItemChess)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_chess = QtWidgets.QFrame(ItemChess)
        self.frame_chess.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chess.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chess.setObjectName("frame_chess")
        self.lb_chess_ico = QtWidgets.QLabel(self.frame_chess)
        self.lb_chess_ico.setGeometry(QtCore.QRect(10, 10, 131, 131))
        self.lb_chess_ico.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.lb_chess_ico.setText("")
        self.lb_chess_ico.setObjectName("lb_chess_ico")
        self.lb_chess_level = QtWidgets.QLabel(self.frame_chess)
        self.lb_chess_level.setGeometry(QtCore.QRect(0, 0, 151, 31))
        self.lb_chess_level.setStyleSheet("")
        self.lb_chess_level.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_chess_level.setObjectName("lb_chess_level")
        self.lb_chess_name = QtWidgets.QLabel(self.frame_chess)
        self.lb_chess_name.setGeometry(QtCore.QRect(0, 110, 151, 41))
        self.lb_chess_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_chess_name.setObjectName("lb_chess_name")
        self.horizontalLayout.addWidget(self.frame_chess)

        self.retranslateUi(ItemChess)
        QtCore.QMetaObject.connectSlotsByName(ItemChess)

    def retranslateUi(self, ItemChess):
        _translate = QtCore.QCoreApplication.translate
        ItemChess.setWindowTitle(_translate("ItemChess", "Form"))
        self.lb_chess_level.setText(_translate("ItemChess", "★★★"))
        self.lb_chess_name.setText(_translate("ItemChess", "嘉文四世"))
