# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item_equip.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemEquip(object):
    def setupUi(self, ItemEquip):
        ItemEquip.setObjectName("ItemEquip")
        ItemEquip.resize(117, 80)
        self.verticalLayout = QtWidgets.QVBoxLayout(ItemEquip)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ItemEquip)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_big = QtWidgets.QLabel(self.frame)
        self.lb_big.setText("")
        self.lb_big.setObjectName("lb_big")
        self.horizontalLayout_2.addWidget(self.lb_big)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_samll1 = QtWidgets.QLabel(self.frame)
        self.lb_samll1.setText("")
        self.lb_samll1.setObjectName("lb_samll1")
        self.verticalLayout_2.addWidget(self.lb_samll1)
        self.lb_samll2 = QtWidgets.QLabel(self.frame)
        self.lb_samll2.setText("")
        self.lb_samll2.setObjectName("lb_samll2")
        self.verticalLayout_2.addWidget(self.lb_samll2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ItemEquip)
        QtCore.QMetaObject.connectSlotsByName(ItemEquip)

    def retranslateUi(self, ItemEquip):
        _translate = QtCore.QCoreApplication.translate
        ItemEquip.setWindowTitle(_translate("ItemEquip", "Form"))
