# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item_strategy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemStrategy(object):
    def setupUi(self, ItemStrategy):
        ItemStrategy.setObjectName("ItemStrategy")
        ItemStrategy.resize(333, 53)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ItemStrategy)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(ItemStrategy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.h_box = QtWidgets.QHBoxLayout(self.frame)
        self.h_box.setContentsMargins(2, 2, 2, 2)
        self.h_box.setSpacing(2)
        self.h_box.setObjectName("h_box")
        self.lb_tphot = QtWidgets.QLabel(self.frame)
        self.lb_tphot.setStyleSheet("")
        self.lb_tphot.setText("")
        self.lb_tphot.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tphot.setObjectName("lb_tphot")
        self.h_box.addWidget(self.lb_tphot)
        self.lb_title = QtWidgets.QLabel(self.frame)
        self.lb_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_title.setObjectName("lb_title")
        self.h_box.addWidget(self.lb_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_box.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(ItemStrategy)
        QtCore.QMetaObject.connectSlotsByName(ItemStrategy)

    def retranslateUi(self, ItemStrategy):
        _translate = QtCore.QCoreApplication.translate
        ItemStrategy.setWindowTitle(_translate("ItemStrategy", "Form"))
        self.lb_title.setText(_translate("ItemStrategy", "【猛拍按钮专属】6堡垒卫士4赛博老大2高级工程师"))
