# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item_job_and_race.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemJobAndRace(object):
    def setupUi(self, ItemJobAndRace):
        ItemJobAndRace.setObjectName("ItemJobAndRace")
        ItemJobAndRace.resize(147, 64)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ItemJobAndRace)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(ItemJobAndRace)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_ico = QtWidgets.QFrame(self.frame)
        self.frame_ico.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ico.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ico.setObjectName("frame_ico")
        self.horizontalLayout_2.addWidget(self.frame_ico)
        self.lb_name = QtWidgets.QLabel(self.frame)
        self.lb_name.setObjectName("lb_name")
        self.horizontalLayout_2.addWidget(self.lb_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(ItemJobAndRace)
        QtCore.QMetaObject.connectSlotsByName(ItemJobAndRace)

    def retranslateUi(self, ItemJobAndRace):
        _translate = QtCore.QCoreApplication.translate
        ItemJobAndRace.setWindowTitle(_translate("ItemJobAndRace", "Form"))
        self.lb_name.setText(_translate("ItemJobAndRace", "重装战士"))
